export const formatInfos: Record<string, Record<string, string>> = {
  f_TPR: {
    r86400: "Last 24 hours",
    r172800: "Last 2 days",
    r604800: "Last 7 days",
    r1209600: "Last 14 days",
    r2592000: "Last 30 days",
    r0: "Any time",
  },
  f_JT: {
    "1": "Full-time",
    "2": "Part-time",
    "3": "Contract",
    "4": "Freelance",
    "5": "Internship",
    "6": "Temporary",
  },
  f_WT: {
    "1": "On-site",
    "2": "Remote",
    "3": "Hybrid",
  },
  f_E: {
    "1": "Internship",
    "2": "Entry level",
    "3": "Associate (Pleno)",
    "4": "Mid-Senior level (Sênior)",
    "5": "Director (Gerente)",
    "6": "Executive (Executivo)",
  },
  f_I: {
    "4": "Financial Services",
    "6": "Construction",
    "7": "Education",
    "27": "Real Estate",
    "34": "Healthcare",
    "43": "Retail",
    "47": "Consumer Goods",
    "54": "Legal",
    "70": "Oil & Energy",
    "73": "Public Safety",
    "74": "Publishing",
    "80": "Telecommunications",
    "84": "Transportation",
    "91": "Utilities",
    "94": "Information Technology",
    "96": "Software & Internet",
    "97": "Sports",
    "98": "Staffing & Recruiting",
    "100": "Non-profit Organization",
    "109": "Government Administration",
    "119": "Design",
    "120": "Aviation",
    "122": "Food & Beverages",
    "124": "Hospitality",
    "137": "Human Resources",
    "138": "Import & Export",
    "143": "Logistics & Supply Chain",
    "144": "Luxury Goods & Jewelry",
    "147": "Marketing & Advertising",
    "148": "Mechanical or Industrial Engineering",
    "149": "Media Production",
    "150": "Medical Devices",
    "151": "Mining & Metals",
    "152": "Motion Pictures and Film",
    "153": "Museums and Institutions",
    "154": "Music",
    "155": "Nanotechnology",
    "157": "Newspapers",
    "158": "Nonprofit Organization Management",
    "159": "Oil & Energy",
    "160": "Online Media",
    "161": "Outsourcing/Offshoring",
    "162": "Package/Freight Delivery",
    "163": "Packaging and Containers",
    "164": "Paper & Forest Products",
    "165": "Performing Arts",
    "166": "Pharmaceuticals",
    "167": "Philanthropy",
    "168": "Photography",
    "169": "Plastics",
    "170": "Political Organization",
    "171": "Primary/Secondary Education",
    "172": "Printing",
    "173": "Professional Training & Coaching",
    "174": "Program Development",
    "175": "Public Policy",
    "176": "Public Relations and Communications",
    "177": "Public Safety",
    "178": "Publishing",
    "179": "Railroad Manufacture",
    "180": "Ranching",
    "181": "Real Estate",
    "182": "Recreational Facilities and Services",
    "183": "Religious Institutions",
    "184": "Renewables & Environment",
    "185": "Research",
    "186": "Restaurants",
    "187": "Retail",
    "188": "Security and Investigations",
    "189": "Semiconductors",
    "190": "Shipbuilding",
    "191": "Sporting Goods",
    "192": "Sports",
    "193": "Staffing and Recruiting",
    "194": "Supermarkets",
    "195": "Telecommunications",
    "196": "Textiles",
    "197": "Think Tanks",
    "198": "Tobacco",
    "199": "Translation and Localization",
    "200": "Transportation/Trucking/Railroad",
    "201": "Utilities",
    "202": "Venture Capital & Private Equity",
    "203": "Veterinary",
    "204": "Warehousing",
    "205": "Wholesale",
    "206": "Wine and Spirits",
    "207": "Wireless",
    "208": "Writing and Editing"
  },
  f_C: {
    "1441": "Microsoft",
    "1035": "Google",
    "1337": "Amazon",
    "10667": "Apple",
    "16164": "Meta (Facebook)",
    "162479": "Netflix",
    "238": "LinkedIn",
    "1753": "IBM",
    "2643": "Intel",
    "1017": "Adobe",
    "1320": "Dell Technologies",
    "1398": "Oracle",
    "1003": "Accenture",
    "1093": "Capgemini",
    "1083": "Cisco",
    "1470": "SAP",
    "177": "Atlassian",
    "1333": "Salesforce",
    "3566": "Spotify",
  }
};


export const fieldLabels: Record<string, string> = {
  f_E: "Experience Level",
  f_JT: "Job Type",
  f_TPR: "Date Posted",
  f_WT: "Workplace Type",
  f_I: "Industry",
  f_C: "Company",
  keywords: "Keywords",
  location: "Location",
  position: "Position",
  pageNum: "Page Number",
};